#!/bin/bash  
echo "Powered by Cinvestav"



echo "Cloning Eigen3 repository"
#git clone -b 3.4.0 https://gitlab.com/libeigen/eigen.git
git clone --depth 1 --branch before-git-migration https://gitlab.com/libeigen/eigen.git
mv eigen eigen3



echo "Building Geometric Multibody Dynamics Library"
mkdir build
cd build
cmake -Wno-dev .. -DCMAKE_BUILD_TYPE=RELEASE
make



echo "Creating static library"
cd ..
mkdir -p geombd/cmake/linux-64
cat << 'EOF' >geombd/cmake/linux-64/geombd-config.cmake
# Autogenerated file.
# Do not edit.
# Do not change location.

message("Setting GeoMBD for linux-64")

get_filename_component(_cur_dir ${CMAKE_CURRENT_LIST_FILE} PATH)
set(_root_dir "${_cur_dir}/../../")
get_filename_component(ROOT_DIR ${_root_dir} ABSOLUTE)


set(GeoMBD_INCLUDE_DIRS "${ROOT_DIR}/include;" CACHE INTERNAL "" FORCE)
set(GeoMBD_LIBRARIES "${ROOT_DIR}/lib/linux-64/libgeombd.a;" CACHE INTERNAL "" FORCE)

set(GeoMBD_TARGET "GeoMBD" CACHE INTERNAL "" FORCE)

set(GeoMBD_PACKAGE_FOUND "TRUE" CACHE INTERNAL "" FORCE)

set(GeoMBD_DEPENDS "" CACHE INTERNAL "" FORCE)
EOF
mkdir geombd/include
cp -r include/geombd geombd/include
mkdir -p geombd/lib/linux-64
cp build/libgeombd.a geombd/lib/linux-64



echo "Build examples with static library"
mkdir examples_static/build
cd examples_static/build
cmake -Wno-dev .. -DCMAKE_BUILD_TYPE=RELEASE
make
